mipi-display-changes

diff --git a/meta-digi-dey/recipes-graphics/lvgl/files/lvgl-demo-init b/meta-digi-dey/recipes-graphics/lvgl/files/lvgl-demo-init
--- a/meta-digi-dey/recipes-graphics/lvgl/files/lvgl-demo-init
+++ b/meta-digi-dey/recipes-graphics/lvgl/files/lvgl-demo-init
@@ -89,7 +89,7 @@ stop() {
 start() {
     check_is_running && { log warning "start: ${DEMO_NAME} ALREADY running"; exit 0; }
     wait_for_wayland
-    killall weston
+    #killall weston
 
 	if [ ! -d "$UPDATE_DIR" ]; then
 		echo "Directory $UPDATE_DIR does not exist. Creating it..."
@@ -104,7 +104,15 @@ start() {
 	# Disable the cursor when displaying at full screen on fbdev
     echo "0" > /sys/class/graphics/fbcon/cursor_blink
 
-        #fbset -xres 800 -yres 480
+    #fbset -xres 800 -yres 480
+	
+	# Modify the IPv4 route metric for eth0
+	if nmcli connection modify "eth0" ipv4.route-metric 1000; then
+		echo "[OK] Successfully updated route metric for eth0 to 1000."
+	else
+		echo "[ERROR] Failed to update route metric for eth0." >&2
+	fi
+
     LOG_FILE="/var/log/application_log"
     MAX_LOG_SIZE=5120
 
